# Generated by Django 4.1.5 on 2023-01-04 01:42

import cpf_field.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iqoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqoption',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='email_brokerage',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail de Registro na Corretora'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='mobile',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='password_brokerage',
            field=models.CharField(max_length=128, null=True, verbose_name='Senha de Acesso na Corretora'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data de Registro'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='registration_date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Alteração'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='trader_brokerage',
            field=models.CharField(choices=[('iqoption', 'IQ Option')], default='iqoption', max_length=10, null=True, verbose_name='Corretora Trader'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='user_name_brokerage',
            field=models.CharField(max_length=150, null=True, verbose_name='Usuário de Registro na Corretora'),
        ),
    ]
