# Generated by Django 4.1.5 on 2023-01-03 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_delete_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='registration_date_update',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Última Alteração'),
        ),
    ]
