# Generated by Django 4.1.5 on 2023-01-03 06:20

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_delete_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
