# Generated by Django 4.1.5 on 2023-01-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_registration_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='registration_date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Alteração'),
        ),
    ]
